const app = require("../app")

const categoryRoute = require('./category-route')
const subCategoryRoute = require('./sub-category-route')
const brandsRoute = require('./brands-route')
const productRoute = require('./product-route')
const userRoute = require('./user-route')
const authRoute = require('./auth-route')
const reviewRoute = require('./review-route')
const wishListRoute = require('./wish-list-route')
const addressRoute = require('./address-route')
const couponRoute = require('./coupon-route')
const cartRoute = require('./cart-route')

exports.mountRoutes = (app) => {
   app.use('/api/v1/categories', categoryRoute)
   app.use('/api/v1/subcategories', subCategoryRoute)
   app.use('/api/v1/brands', brandsRoute)
   app.use('/api/v1/products', productRoute)
   app.use('/api/v1/users', userRoute)
   app.use('/api/v1/auth', authRoute)
   app.use('/api/v1/review', reviewRoute)
   app.use('/api/v1/wishList', wishListRoute)
   app.use('/api/v1/addresses', addressRoute)
   app.use('/api/v1/coupons', couponRoute)
   app.use('/api/v1/cart', cartRoute)
}